import os
import sys
from pathlib import Path

from Engine.config import project_path
from Engine.executor import run_task


def create_project_structure(name: str):
    base = project_path(name)

    dirs = [
        base,
        base / "Tasks",
        base / "Logs",
        base / "src",
    ]

    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)

    # базовый README
    (base / "README.md").write_text(
        f"# {name}\n\nGenerated by AIDOS\n",
        encoding="utf-8"
    )

    return base


def init_project(idea: str):
    print("[AIDOS] INIT PROJECT")
    print(f"[IDEA] {idea}")

    project_name = idea.lower().replace(" ", "_")

    create_project_structure(project_name)

    print("[AIDOS] PROJECT STRUCTURE CREATED")

    # запускаем planner сразу
    run_task(idea, project_name)

    print("\n[AIDOS] INIT COMPLETE")


if __name__ == "__main__":
    idea = " ".join(sys.argv[1:])

    if not idea:
        print("Usage: python3 Engine/init.py \"idea\"")
        exit(1)

    init_project(idea)